include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - build/**
  errors:
    avoid_print: warning

linter:
  rules:
    avoid_print: false
    prefer_interpolation_to_compose_strings: false
